// Command seedusers inserts a batch of demo users into the `users` table so the
// Admin Portal (GET /admin/users) has lifelike data to browse. Dev/demo only.
//
// The dataset is mapped from a real account export (Kiddilab). Only the fields
// the `users` table has are kept:
//   - full name      -> name
//   - phone          -> phone (masked middle digits filled with random values)
//   - username       -> email (username + "@gmail.com", sanitized; a username
//                       that is already an email is used as-is)
// Everything else from the source (address, order code, the source's own id)
// is dropped; `id` is generated by our system (UUID default).
//
// Two modes:
//
//	# A) Connect directly and insert (local dev DB, or any reachable DB):
//	DATABASE_URL="postgres://wearwhere:wearwhere@localhost:5432/wearwhere?sslmode=disable" \
//	    go run ./cmd/seedusers
//
//	# B) Emit SQL to stdout (for DBs reachable only via psql, e.g. the GCP VM
//	#    where Postgres is internal-only — pipe into the container's psql):
//	go run ./cmd/seedusers -sql | \
//	    ssh -i ~/.ssh/wearwhere-demo deploy@34.87.41.62 \
//	      'docker exec -i wearwhere-postgres-1 psql -U wearwhere -d wearwhere -v ON_ERROR_STOP=1'
//
// Idempotent: re-running skips users whose phone already exists
// (ON CONFLICT (phone) DO NOTHING).
package main

import (
	"context"
	"flag"
	"fmt"
	"log"
	"os"
	"strings"

	"github.com/jackc/pgx/v5/pgxpool"
)

const defaultDBURL = "postgres://wearwhere:wearwhere@localhost:5432/wearwhere?sslmode=disable"

// seedUser is one row to insert: only the columns the users table has.
type seedUser struct {
	Name  string
	Phone string // 10-digit VN mobile; masked middle digits filled with random values
	Email string // derived from the source username
}

// 28 users mapped from the Kiddilab account list (full name, phone, email).
var users = []seedUser{
	{"Nguyễn Ngọc Quý", "0973651109", "quynn1@gmail.com"},
	{"Nguyễn Y Mai", "0368204935", "ngoanxinhyeu@gmail.com"},
	{"Đỗ Văn Hùng", "0867519963", "hungdova@gmail.com"},
	{"Nguyễn Tùng Lâm", "0364187294", "phungdz@gmail.com"},
	{"Chi Nguyễn", "0915730510", "nguyenchi@gmail.com"},
	{"Phạm Thị Khánh Huyền", "0394268750", "khanhhuyen@gmail.com"},
	{"Nguyễn Thị Tâm Anh", "0917894146", "tamanh2004@gmail.com"},
	{"Nguyễn Thế Tùng", "0813502848", "ntdbeu@gmail.com"},
	{"Lê Hoàng Nam", "0961473866", "hoangnam9tuoi@gmail.com"},
	{"Trần Quang Anh", "0356981226", "namanh28@gmail.com"},
	{"Nguyễn Tùng Dương", "0342750462", "duongsut8904s@gmail.com"},
	{"Nguyễn Đức Tâm", "0916308959", "lenguyennhatanh@gmail.com"},
	{"Nguyễn Minh Đức", "0365129478", "minhduc@gmail.com"},
	{"Nguyễn Thị Thúy", "0974860974", "dangduc1@gmail.com"},
	{"Nguyễn Quốc Việt", "0873914520", "quocviet12399@gmail.com"},
	{"Nguyễn Thanh Thu", "0398642068", "chauquangdang@gmail.com"},
	{"Đoàn Thị Minh Diệp", "0971538227", "dipbull13@gmail.com"},
	{"Vương Hải Vũ", "0376205916", "tintin2004@gmail.com"},
	{"Lê Thị Hân", "0974351798", "han123@gmail.com"},
	{"Ngô Anh Ngọc", "0948670516", "ngoc2016@gmail.com"},
	{"Mạc Hùng Cường", "0325914221", "trontron@gmail.com"},
	{"Vũ Hải Dương", "0973486094", "dvu784796@gmail.com"},
	{"Nguyễn trung Nam", "0337150995", "namben1234@gmail.com"},
	{"Lê Kỳ Tuấn", "0935624898", "alekiky@gmail.com"},
	{"Nguyễn mai Hồng trang", "0918073456", "trangcao12@gmail.com"},
	{"Đỗ Mai Anh", "0942596204", "maianh2212@gmail.com"},
	{"Đào Hải Đăng", "0976318065", "haidang123@gmail.com"},
	{"Vũ Chí Nguyện", "0934857669", "nguyenvu@gmail.com"},
}

func main() {
	emitSQL := flag.Bool("sql", false, "print INSERT statements to stdout instead of connecting to a DB")
	flag.Parse()

	if *emitSQL {
		fmt.Print(buildSQL())
		return
	}
	runDirect()
}

// buildSQL renders the seed as a single transactional SQL script.
func buildSQL() string {
	var b strings.Builder
	b.WriteString("BEGIN;\n")
	for _, u := range users {
		fmt.Fprintf(&b,
			"INSERT INTO users (name, phone, email) VALUES (%s, %s, %s) "+
				"ON CONFLICT (phone) DO NOTHING;\n",
			sqlStr(u.Name), sqlStr(u.Phone), sqlStr(u.Email),
		)
	}
	b.WriteString("COMMIT;\n")
	return b.String()
}

// sqlStr quotes a string as a SQL literal, or returns NULL for the empty string.
func sqlStr(s string) string {
	if s == "" {
		return "NULL"
	}
	return "'" + strings.ReplaceAll(s, "'", "''") + "'"
}

// runDirect connects via DATABASE_URL and inserts the users with parameterized
// queries.
func runDirect() {
	dbURL := os.Getenv("DATABASE_URL")
	if dbURL == "" {
		dbURL = defaultDBURL
		log.Printf("DATABASE_URL not set, using dev default: %s", dbURL)
	}

	ctx := context.Background()
	pool, err := pgxpool.New(ctx, dbURL)
	if err != nil {
		log.Fatalf("connect db: %v", err)
	}
	defer pool.Close()
	if err := pool.Ping(ctx); err != nil {
		log.Fatalf("ping db: %v", err)
	}

	const q = `INSERT INTO users (name, phone, email) VALUES ($1, $2, $3)
	           ON CONFLICT (phone) DO NOTHING`

	inserted, skipped := 0, 0
	for _, u := range users {
		tag, err := pool.Exec(ctx, q, u.Name, u.Phone, u.Email)
		if err != nil {
			log.Fatalf("insert %q: %v", u.Name, err)
		}
		if tag.RowsAffected() == 1 {
			inserted++
		} else {
			skipped++
			log.Printf("skip (phone exists): %s", u.Phone)
		}
	}

	log.Printf("done: %d inserted, %d skipped (of %d).", inserted, skipped, len(users))
}
